# Generated by Django 5.2 on 2025-04-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NpsQuestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_type', models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True)),
                ('lang_id', models.CharField(blank=True, max_length=3, null=True)),
                ('question_number', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('regexp_replace', models.CharField(max_length=500)),
                ('question_name', models.CharField(max_length=100)),
                ('question_type', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'nps_questions',
                'managed': False,
            },
        ),
    ]
