# Generated by Django 5.2.1 on 2025-05-21 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_age_group_city_survey_survey_nps_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityRegionNps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=50)),
                ('retail_region_name', models.CharField(max_length=30)),
                ('total_valid', models.BigIntegerField()),
                ('promotors', models.BigIntegerField()),
                ('passives', models.BigIntegerField()),
                ('detractors', models.BigIntegerField()),
                ('avg_nps', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'mv_city_region_nps',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SurveyResponseCounts',
            fields=[
                ('question_type', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('response_count', models.BigIntegerField()),
            ],
            options={
                'db_table': 'survey_response_counts',
                'managed': False,
            },
        ),
    ]
