# Generated by Django 5.2.1 on 2025-05-21 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('agent', 'Agent')], default='agent', max_length=10),
        ),
    ]
